//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNTraining.WebApi.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumDescriptionResources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumDescriptionResources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NNTraining.WebApi.Contracts.Resources.EnumDescriptionResources.en", typeof(EnumDescriptionResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification of numbers.
        /// </summary>
        internal static string ClassifyMnist {
            get {
                return ResourceManager.GetString("ClassifyMnist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification of pictures.
        /// </summary>
        internal static string ClassifyPictures {
            get {
                return ResourceManager.GetString("ClassifyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data prediction.
        /// </summary>
        internal static string DataPrediction {
            get {
                return ResourceManager.GetString("DataPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of predict.
        /// </summary>
        internal static string ErrorOfPredict {
            get {
                return ResourceManager.GetString("ErrorOfPredict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of training model.
        /// </summary>
        internal static string ErrorOfTrainingModel {
            get {
                return ResourceManager.GetString("ErrorOfTrainingModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialized.
        /// </summary>
        internal static string Initialized {
            get {
                return ResourceManager.GetString("Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need a parameters.
        /// </summary>
        internal static string NeedAParameters {
            get {
                return ResourceManager.GetString("NeedAParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paints.
        /// </summary>
        internal static string Paints {
            get {
                return ResourceManager.GetString("Paints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to training.
        /// </summary>
        internal static string ReadyToTraining {
            get {
                return ResourceManager.GetString("ReadyToTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still predict.
        /// </summary>
        internal static string StillPredict {
            get {
                return ResourceManager.GetString("StillPredict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still training.
        /// </summary>
        internal static string StillTraining {
            get {
                return ResourceManager.GetString("StillTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trained.
        /// </summary>
        internal static string Trained {
            get {
                return ResourceManager.GetString("Trained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting training.
        /// </summary>
        internal static string WaitingTraining {
            get {
                return ResourceManager.GetString("WaitingTraining", resourceCulture);
            }
        }
    }
}
