//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNTraining.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumDescriptionResources_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumDescriptionResources_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NNTraining.Contracts.Resources.EnumDescriptionResources.ru", typeof(EnumDescriptionResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распознавание чисел.
        /// </summary>
        internal static string ClassifyMnist {
            get {
                return ResourceManager.GetString("ClassifyMnist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Классификация изображений.
        /// </summary>
        internal static string ClassifyPictures {
            get {
                return ResourceManager.GetString("ClassifyPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вычисление закономерностей.
        /// </summary>
        internal static string DataPrediction {
            get {
                return ResourceManager.GetString("DataPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалена.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициализованна.
        /// </summary>
        internal static string Initialized {
            get {
                return ResourceManager.GetString("Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо задать параметры.
        /// </summary>
        internal static string NeedAParameters {
            get {
                return ResourceManager.GetString("NeedAParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рисование.
        /// </summary>
        internal static string Paints {
            get {
                return ResourceManager.GetString("Paints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готова к тренировке.
        /// </summary>
        internal static string ReadyToTraining {
            get {
                return ResourceManager.GetString("ReadyToTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В процессе тренировки.
        /// </summary>
        internal static string StillTraining {
            get {
                return ResourceManager.GetString("StillTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готова к использованию.
        /// </summary>
        internal static string Trained {
            get {
                return ResourceManager.GetString("Trained", resourceCulture);
            }
        }
    }
}
